# Generated by Django 3.1.5 on 2021-01-29 06:27

import apps.Utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('file', models.ImageField(upload_to=apps.Utils.models.path_and_rename)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('table', models.CharField(db_index=True, default='photos', max_length=50)),
            ],
            options={
                'db_table': 'Imagenes',
            },
        ),
    ]
