# Generated by Django 3.1.1 on 2020-10-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aplicacion',
            table='Aplicacion',
        ),
        migrations.AlterModelTable(
            name='grupo',
            table='Grupo',
        ),
        migrations.AlterModelTable(
            name='permiso',
            table='Permiso',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
