# Generated by Django 3.1.3 on 2020-11-21 02:15

import apps.Matriculas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('diagnostico_clinico', models.TextField(blank=True, null=True)),
                ('numero_matricula', models.CharField(default='', max_length=155)),
                ('matricula', models.TextField(blank=True, null=True)),
                ('aporte_voluntario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('info_faltas', models.JSONField(default=apps.Matriculas.models.AlumnoAula.default_info_faltas)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.alumno')),
            ],
            options={
                'db_table': 'AlumnoAulas',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('grado', models.PositiveSmallIntegerField()),
                ('horas_presencial', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('objetivo_especifico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=155)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_fin_clases', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsables', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PeriodoLectivos',
            },
        ),
        migrations.CreateModel(
            name='NotaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('alumno_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.alumnoaula')),
            ],
            options={
                'db_table': 'NotaAlumnos',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('grado', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jornada', models.CharField(default='MATUTINA', max_length=50)),
                ('alumnos', models.ManyToManyField(blank=True, through='Matriculas.AlumnoAula', to='Personas.Alumno')),
                ('docentes', models.ManyToManyField(to='Personas.Personal')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.periodolectivo')),
            ],
            options={
                'db_table': 'Aulas',
            },
        ),
        migrations.AddField(
            model_name='alumnoaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.aula'),
        ),
    ]
