# Generated by Django 3.1.3 on 2021-01-10 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnoaula',
            name='info_faltas',
        ),
        migrations.AddField(
            model_name='alumnoaula',
            name='total_faltas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.alumnoaula')),
            ],
            options={
                'db_table': 'FaltasAlumno',
            },
        ),
    ]
