# Generated by Django 3.1.3 on 2021-01-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0002_auto_20210109_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoaula',
            name='estado_matricula',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Creada'), (1, 'Anulada'), (2, 'Finalizada')], default=0),
        ),
    ]
