# Generated by Django 3.1.3 on 2021-01-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0003_alumnoaula_estado_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoaula',
            name='numero_matricula',
            field=models.CharField(default='', max_length=155, unique=True),
        ),
    ]
