# Generated by Django 3.1.3 on 2021-01-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0004_auto_20210109_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodolectivo',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cerrado'), (1, 'Abierto')], default=1),
        ),
    ]
