# Generated by Django 3.1.5 on 2021-01-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0006_auto_20210119_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoaula',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
