# Generated by Django 3.1.5 on 2021-02-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0007_alumnoaula_motivo_anulacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaAlumno',
        ),
    ]
