# Generated by Django 3.1.5 on 2021-02-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_personal_area_de_trabajo'),
        ('Matriculas', '0009_delete_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodolectivo',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='director', to='Personas.personal'),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='coordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='coordinador', to='Personas.personal'),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='sub_coordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_coordinador', to='Personas.personal'),
        ),
    ]
