# Generated by Django 3.1.5 on 2021-02-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matriculas', '0007_alumnoaula_motivo_anulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='NotaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('resultado', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_aula', to='Matriculas.alumnoaula')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notas.componente')),
            ],
            options={
                'db_table': 'NotasAlumno',
            },
        ),
    ]
