# Generated by Django 3.1.5 on 2021-02-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0003_evidencianotaalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencianotaalumno',
            name='nota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='Notas.notaalumno'),
        ),
    ]
