# Generated by Django 3.1.1 on 2020-10-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_faltas', models.PositiveSmallIntegerField(default=0)),
                ('tratamiento', models.TextField()),
                ('diagnostico', models.TextField()),
                ('matroicula', models.TextField()),
                ('aporte_voluntario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.alumno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('grado', models.PositiveSmallIntegerField()),
                ('horas_presencial', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=50)),
                ('objetivo_especifico', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=155)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_fin_clases', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsablePeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('rol', models.CharField(max_length=155)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.periodolectivo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.docente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='periodolectivo',
            name='responsables',
            field=models.ManyToManyField(through='Matriculas.ResponsablePeriodo', to='Personas.Docente'),
        ),
        migrations.CreateModel(
            name='NotaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('alumno_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.alumnoaula')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.nota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('grado', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('docentes', models.ManyToManyField(to='Personas.Docente')),
                ('estudiantes', models.ManyToManyField(blank=True, through='Matriculas.AlumnoAula', to='Personas.Alumno')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.periodolectivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumnoaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.aula'),
        ),
        migrations.AddField(
            model_name='alumnoaula',
            name='notas',
            field=models.ManyToManyField(through='Matriculas.NotaEstudiante', to='Matriculas.Nota'),
        ),
    ]
