# Generated by Django 3.1.1 on 2020-10-16 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnoaula',
            old_name='matroicula',
            new_name='diagnostico_final',
        ),
        migrations.AddField(
            model_name='alumnoaula',
            name='matricula',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
