# Generated by Django 3.1.1 on 2020-10-16 03:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0002_auto_20201015_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('materia', models.JSONField()),
                ('notas', models.JSONField(default=[])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notaestudiante',
            name='alumno_aula',
        ),
        migrations.RemoveField(
            model_name='notaestudiante',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='alumnoaula',
            name='notas',
        ),
        migrations.AddField(
            model_name='alumnoaula',
            name='faltas',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnoaula',
            name='numero_matricula',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='jornada',
            field=models.CharField(default='MATUTINA', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumnoaula',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='NotaEstudiante',
        ),
        migrations.AddField(
            model_name='notamateria',
            name='alumno_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.alumnoaula'),
        ),
    ]
