# Generated by Django 3.1.1 on 2020-10-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20201014_2331'),
        ('Matriculas', '0003_auto_20201015_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodolectivo',
            name='responsables',
            field=models.ManyToManyField(default=[], through='Matriculas.ResponsablePeriodo', to='Personas.Docente'),
        ),
    ]
