# Generated by Django 3.1.1 on 2020-10-16 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0004_auto_20201015_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='horas_presencial',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='objetivo_especifico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
