# Generated by Django 3.1.1 on 2020-10-16 05:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0005_auto_20201015_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoaula',
            name='diagnostico_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnoaula',
            name='faltas',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='notamateria',
            name='materia',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='notamateria',
            name='notas',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
