# Generated by Django 3.1.1 on 2020-10-18 04:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0006_auto_20201016_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoaula',
            name='numero_matricula',
            field=models.CharField(default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='notamateria',
            name='notas',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
