# Generated by Django 3.1.3 on 2020-11-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Discapacidades',
            },
        ),
        migrations.CreateModel(
            name='FuncionPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'RolesPersonal',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('tiene_discapacidad', models.CharField(default='NO', max_length=10)),
                ('carnet_conadis', models.CharField(default='NO REGISTRA', max_length=50)),
                ('porcentaje_discapacidad', models.PositiveSmallIntegerField(default=0)),
                ('etnia', models.CharField(max_length=30)),
                ('tipo_sangre', models.CharField(max_length=30)),
                ('pais_residencia', models.CharField(max_length=150)),
                ('provincia_residencia', models.CharField(max_length=150)),
                ('canton_residencia', models.CharField(max_length=150)),
                ('parroquia_residencia', models.CharField(max_length=150)),
                ('direccion_domiciliaria', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_uno', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_dos', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('foto', models.URLField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('discapacidades', models.ManyToManyField(blank=True, to='Personas.Discapacidad')),
            ],
            options={
                'db_table': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('info', models.JSONField(blank=True, null=True)),
                ('historico', models.JSONField(blank=True, null=True)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.funcionpersonal')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.persona')),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('padre', models.JSONField(blank=True, null=True)),
                ('madre', models.JSONField(blank=True, null=True)),
                ('representante', models.JSONField(blank=True, null=True)),
                ('contacto_emergencia', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.CharField(blank=True, max_length=20, null=True)),
                ('trastornos_asociados', models.TextField(blank=True, null=True)),
                ('grado_dependencia', models.TextField(blank=True, null=True)),
                ('bono', models.CharField(default='Ninguno', max_length=50)),
                ('tipo_bono', models.CharField(max_length=50)),
                ('afiliacion_iess', models.CharField(max_length=10)),
                ('quintil_pobreza', models.CharField(max_length=10)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='Personas.persona')),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
    ]
