# Generated by Django 3.1.3 on 2020-12-21 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20201127_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionpersonal',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
