# Generated by Django 3.1.5 on 2021-01-17 21:29

from django.db import migrations, models

from utils.constants.DefaultValuesModels import NO_REGISTRA


class Migration(migrations.Migration):
    dependencies = [
        ('Personas', '0003_funcionpersonal_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='info',
            new_name='meta_data',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='funcion',
        ),
        migrations.AddField(
            model_name='personal',
            name='funciones',
            field=models.ManyToManyField(blank=True, to='Personas.FuncionPersonal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_titulo',
            field=models.CharField(default=NO_REGISTRA, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='titulo',
            field=models.CharField(default=NO_REGISTRA, max_length=150),
            preserve_default=False,
        ),
    ]
