# Generated by Django 3.1.5 on 2021-01-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0004_auto_20210117_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='area_de_trabajo',
            field=models.TextField(blank=True, default='NO REGISTRA', null=True),
        ),
    ]
