# Generated by Django 3.1.5 on 2021-02-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_personal_area_de_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
