# Generated by Django 3.1.1 on 2020-10-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('grado', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_titulo', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('padre', models.JSONField(blank=True, null=True)),
                ('madre', models.JSONField(blank=True, null=True)),
                ('representante', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_faltas', models.PositiveSmallIntegerField(default=0)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.aula')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('grado', models.PositiveSmallIntegerField()),
                ('horas_presencial', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=50)),
                ('objetivo_especifico', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=155)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_fin_clases', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsablePeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('rol', models.CharField(max_length=155)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.periodolectivo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.docente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('foto', models.URLField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('calle_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('calle_secundaria', models.CharField(blank=True, max_length=150, null=True)),
                ('lugar_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('tiene_discapacidad', models.CharField(default='NO', max_length=10)),
                ('carnet_conadis', models.CharField(default='NO REGISTRA', max_length=50)),
                ('porcentaje_discapacidad', models.PositiveSmallIntegerField(default=0)),
                ('ocupacion', models.CharField(blank=True, max_length=120, null=True)),
                ('nivel_formacion', models.CharField(blank=True, max_length=255, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('discapacidades', models.ManyToManyField(blank=True, to='Personas.Discapacidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='periodolectivo',
            name='responsables',
            field=models.ManyToManyField(through='Personas.ResponsablePeriodo', to='Personas.Docente'),
        ),
        migrations.CreateModel(
            name='NotaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('estudiante_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.estudianteaula')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.nota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estudianteaula',
            name='notas',
            field=models.ManyToManyField(through='Personas.NotaEstudiante', to='Personas.Nota'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_fk', to='Personas.persona'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.persona'),
        ),
        migrations.AddField(
            model_name='aula',
            name='docentes',
            field=models.ManyToManyField(to='Personas.Docente'),
        ),
        migrations.AddField(
            model_name='aula',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, through='Personas.EstudianteAula', to='Personas.Estudiante'),
        ),
        migrations.AddField(
            model_name='aula',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.periodolectivo'),
        ),
    ]
