# Generated by Django 3.1.1 on 2020-10-14 04:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('foto', models.URLField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('calle_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('calle_secundaria', models.CharField(blank=True, max_length=150, null=True)),
                ('lugar_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('tiene_discapacidad', models.CharField(default='NO', max_length=10)),
                ('carnet_conadis', models.CharField(default='NO REGISTRA', max_length=50)),
                ('porcentaje_discapacidad', models.PositiveSmallIntegerField(default=0)),
                ('ocupacion', models.CharField(blank=True, max_length=120, null=True)),
                ('nivel_formacion', models.CharField(blank=True, max_length=255, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('discapacidades', models.ManyToManyField(blank=True, to='Personas.Discapacidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_titulo', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('padre', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('madre', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('representante', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('contacto_emergencia', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_fk', to='Personas.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
