# Generated by Django 3.1 on 2020-08-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('foto', models.URLField()),
                ('tipo_sangre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveSmallIntegerField()),
                ('calle_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('calle_secundaria', models.CharField(blank=True, max_length=150, null=True)),
                ('lugar_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('discapacidad', models.CharField(blank=True, max_length=5, null=True)),
                ('nivel_discapacidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carnet_conadis', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=120, null=True)),
                ('nivel_formacion', models.CharField(blank=True, max_length=255, null=True)),
                ('extras', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
