# Generated by Django 3.1.1 on 2020-10-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20201014_2331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='Alumno',
        ),
        migrations.AlterModelTable(
            name='discapacidad',
            table='Discapacidad',
        ),
        migrations.AlterModelTable(
            name='docente',
            table='Docente',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
