# Generated by Django 3.1 on 2020-08-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_auto_20200824_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='extras',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
