# Generated by Django 3.1 on 2020-09-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_auto_20200824_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nivel_discapacidad',
        ),
        migrations.AddField(
            model_name='persona',
            name='porcentaje_discapacidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='carnet_conadis',
            field=models.CharField(default='NO REGISTRA', max_length=50),
        ),
    ]
