# Generated by Django 3.1 on 2020-09-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0006_auto_20200903_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_titulo', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=25, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
