# Generated by Django 3.1 on 2020-09-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0007_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='abreviatura',
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('relacion_representante', models.CharField(max_length=100)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madre_fk', to='Personas.persona')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre_fk', to='Personas.persona')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_fk', to='Personas.persona')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representante_fk', to='Personas.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
