# Generated by Django 3.1 on 2020-09-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0009_remove_persona_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
