# Generated by Django 3.1 on 2020-09-18 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0010_estudiante_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.PositiveSmallIntegerField()),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('grado', models.PositiveSmallIntegerField()),
                ('docentes', models.ManyToManyField(to='Personas.Docente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_faltas', models.PositiveSmallIntegerField(default=0)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.aula')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=155)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_fin_clases', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsablePeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('rol', models.CharField(max_length=155)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.periodolectivo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.docente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='periodolectivo',
            name='responsables',
            field=models.ManyToManyField(through='Personas.ResponsablePeriodo', to='Personas.Docente'),
        ),
        migrations.CreateModel(
            name='NotaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('estudiante_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.estudianteaula')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.nota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estudianteaula',
            name='notas',
            field=models.ManyToManyField(through='Personas.NotaEstudiante', to='Personas.Nota'),
        ),
        migrations.AddField(
            model_name='aula',
            name='estudiantes',
            field=models.ManyToManyField(through='Personas.EstudianteAula', to='Personas.Estudiante'),
        ),
        migrations.AddField(
            model_name='aula',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.periodolectivo'),
        ),
    ]
