# Generated by Django 3.1.1 on 2020-09-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0011_auto_20200917_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='informacion_contacto_emergencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
