# Generated by Django 3.1.1 on 2020-09-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0012_auto_20200922_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodolectivo',
            name='responsables',
            field=models.ManyToManyField(blank=True, null=True, through='Personas.ResponsablePeriodo', to='Personas.Docente'),
        ),
    ]
