# Generated by Django 3.1.1 on 2020-09-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0013_auto_20200922_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodolectivo',
            old_name='observacion',
            new_name='observaciones',
        ),
    ]
