# Generated by Django 3.1.1 on 2020-10-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0014_auto_20200922_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='numero',
        ),
        migrations.AddField(
            model_name='aula',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='responsables',
            field=models.ManyToManyField(through='Personas.ResponsablePeriodo', to='Personas.Docente'),
        ),
    ]
