# Generated by Django 3.1.1 on 2020-10-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0015_auto_20201001_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, through='Personas.EstudianteAula', to='Personas.Estudiante'),
        ),
    ]
