# Generated by Django 3.1.1 on 2020-10-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0016_auto_20201002_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.CharField(default='A', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('grado', models.PositiveSmallIntegerField()),
                ('horas_presencial', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=50)),
                ('objetivo_especifico', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
